lockrental/urls.py
from django.contrib import admin
from django.shortcuts import render
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

def welcome(request):
    return render(request, 'welcome.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('main.urls')),
    path('', include('rental.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login, name='login'),
    path('logout', views.signout, name='logout'),
    path('reset_password/<uidb64>/<token>', views.reset_password, name='reset_password'),
    path('forgot_password', views.forgot_password, name='forgot_password'),
    path('activate_account/<uidb64>/<token>', views.activate_account, name='activate_account'),
]

rental/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.stations, name="stations"),
    path('locks', views.locks, name="locks"),
    path('rentals', views.rentals, name="rentals"),
    path('create_rental/<lock_id>', views.create_rental, name="create_rental")
]

rental/models.py
from django.db import models
from main.models import User

# Create your models here.
class LockStation(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=255)
    # You can add other attributes as per your requirements

    def __str__(self):
        return self.name
    
class LockType(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name
    
class Lock(models.Model):
    STATUS_CHOICES = [
        ('RESERVED', 'Reserved'),
        ('RENTED', 'Rented'),
        ('AVAILABLE', 'Available'),
    ]
    
    lock_type = models.ForeignKey(LockType, on_delete=models.CASCADE)
    inner_height = models.IntegerField()
    inner_width = models.IntegerField()
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='AVAILABLE')
    price = models.FloatField()
    station = models.ForeignKey(LockStation, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.lock_type.name
    
class Rental(models.Model):
    lock = models.ForeignKey(Lock, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start = models.DateTimeField()
    end = models.DateTimeField()
    active = models.BooleanField(default=True)
    
    def __str__(self):
        return self.lock.lock_type.name + " - " + self.user.first_name + " " + self.user.last_name + " - " + str(self.start) + " - " + str(self.end)

rental/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from .models import Lock, Rental, LockStation
from .serializers import RentalSerializer
from django.contrib.auth.decorators import login_required

# Create your views here.

def locks(request):
    event_list = Lock.objects.filter(status="AVAILABLE")
    paginator = Paginator(event_list, 6)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'locks.html', {'page_obj': page_obj})

def stations(request):
    stations = LockStation.objects.all()
    paginator = Paginator(stations, 6)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request,'stations.html', {'page_obj': page_obj})

@login_required(login_url="/user/login")
def rentals(request):
    rentals = Rental.objects.filter(user=request.user)
    paginator = Paginator(rentals, 6)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(request, 'rentals.html', {'page_obj': page_obj})

@login_required(login_url="/user/login")
def create_rental(request, lock_id):
    try:
        lock = Lock.objects.get(id=lock_id)
        
        if request.method == "POST":
            if lock .status == 'RENTED':
                return render(request, 'create_rental_form.html', {'lock': lock, 'alert': { 'show': True, 'severity': 'warning', 'message': f"This lock has already been rented" }})
            serializer = RentalSerializer(data=request.POST, context={'request': request, 'lock': lock})
            if serializer.is_valid():
                serializer.save()
                return render(request, 'create_rental_form.html', {'lock': lock, 'alert': { 'show': True, 'severity': 'success', 'message': f"You have succesfully acquired access to the {lock}" }})
            else:
                errors = serializer.errors
                return render(request, 'create_rental_form.html', {'lock': lock, 'alert': { 'show': True, 'severity': 'danger', 'message': ".\t".join([f"{error} - {''.join(errors[error])}" for error in errors]) }})
    except Lock.DoesNotExist:
        lock = None
    return render(request, 'create_rental_form.html', {'lock': lock})

rental/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>LockEase | {%block title%} {% endblock %}</title>
    <!-- Font Awesome -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"
      rel="stylesheet"
    />
    <!-- Google Fonts -->
    <link
      href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
      rel="stylesheet"
    />
    <!-- MDB -->
    <link
      href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.min.css"
      rel="stylesheet"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH"
      crossorigin="anonymous"
    />
    <style>
      .gradient-custom-2 {
        /* fallback for old browsers */
        background: #99BC85;

        /* Chrome 10-25, Safari 5.1-6 */
        background: -webkit-linear-gradient(
          to right,
          #99BC85,
          #E1F0DA,
          #D4E7C5,
          #BFD8AF,
          #99BC85
        );

        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(
          to right,
          #99BC85,
          #E1F0DA,
          #D4E7C5,
          #BFD8AF,
          #99BC85
        );
      }

      @media (min-width: 768px) {
      }
      @media (min-width: 769px) {
        .gradient-custom-2 {
          border-top-right-radius: 0.3rem;
          border-bottom-right-radius: 0.3rem;
        }
      }
    </style>
  </head>
  <body class="d-flex flex-column">
    <!-- Navigation Bar -->
    {% include 'navbar.html' %}

    <!-- Main Content -->
    <div class="flex-grow-1" style="min-height: 60vh;">
      {%block content%} {% endblock %}
    </div>

    <!-- Footer -->
    {% include 'footer.html' %}
    
  </body>
  <script
    src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"
  ></script>
  <!-- MDB -->
  <script
    type="text/javascript"
    src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/7.2.0/mdb.umd.min.js"
  ></script>
</html>

rental/templates/create_rental_form.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Rentals
{% endblock %}

{% block content %}

<div class="container">
    <div>
        {% if lock %}
        <div style="border-left-width: 10px;" class="card card-body my-4 rounded-0 py-5">
            <div class="card-title d-flex align-items-center gap-3">
                <h3>{{ lock.lock_type.name }}</h3>
                <div class="border-bottom flex-grow-1"></div>
                <h3>${{ lock.price }}</h3>
            </div>
            <div class="card-title d-flex align-items-center gap-3">
                <span>Status: {{ lock.status }}</span>
                <div class="flex-grow-"></div>
                <span>Location: {{ lock.station }}, <span style="color: #99BC85;font-weight: bolder;">{{ lock.station.address }}</span></span>
            </div>
        </div>
        {% else %}
        <div style="height: 20vh;font-weight: bolder; border-left-width: 10px;" class="card card-body px-5 my-4 rounded-0">
            <h3 class="h-100 d-flex align-items-center">404 | Sorry! Lock does not exist</h3>
        </div>
        {% endif %}
    </div>

    {% if alert.show %}
    <div class="alert alert-{{ alert.severity }}">
        {{ alert.message }}
    </div>
    {% endif %}
    
    {% if lock %}
    <form action="{% url 'create_rental' lock_id=lock.id %}" method="POST" class="row gap-4">
      {% csrf_token %}
      <div class="form-group">
        <label for="start">Start:</label>
        <input required name="start" type="datetime-local" class="form-control" id="start" name="start" />
      </div>
      <div class="form-group">
        <label for="end">End:</label>
        <input required name="end" type="datetime-local" class="form-control" id="end" name="end" />
      </div>
      <button type="submit" class="btn fa-lg gradient-custom-2">Request Lock</button>
    </form>
    {% endif %}
</div>
{% endblock %}

rental/templates/footer.html
<footer class="">
  <div class="gradient-custom-2 mt-5" style="padding: 5em 2em 2em;">
    <div class="row">
      <div class="col-md-4">
        <h4>Contact Us</h4>
        <p>Email: info@example.com</p>
        <p>Phone: +1234567890</p>
        <p>Address: 123 Main Street, City, Country</p>
      </div>
      <div class="col-md-4">
        <h4>Quick Links</h4>
        <ul>
          <div><a href="/">Home</a></div>
          <div><a href="/events">Events</a></div>
          <div><a href="/about">About Us</a></div>
        </ul>
      </div>
      <div class="col-md-4">
        <h4>Follow Us</h4>
        <ul class="social-icons">
          <div>
            <a href="#"><i class="fab fa-facebook-f"></i> Facebook</a>
          </div>
          <div>
            <a href="#"><i class="fab fa-twitter"></i> Twitter</a>
          </div>
          <div>
            <a href="#"><i class="fab fa-instagram"></i> Instagram</a>
          </div>
          <div>
            <a href="#"><i class="fab fa-linkedin-in"></i> Linkedin</a>
          </div>
        </ul>
      </div>
    </div>
    <hr />
    <div class="row">
      <div class="col-md-12">
        <p class="text-center">&copy; 2024. All rights reserved.</p>
      </div>
    </div>
  </div>
</footer>

rental/templates/locks.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Available Locks
{% endblock %}

{% block content %}

<div class="container">
  <h2 class="mt-2 mb-2" style="font-weight: bolder">Available Locks</h2>
  <div class="row">
    {% if page_obj %}
    <div class="row">
      {% for lock in page_obj %}
      <div class="col-lg-6 p-2 align-items-center">
        <div class="card border-0 rounded-0" style="align-self: center">
          <div class="card-body">
            <h5 class="card-title text-secondary">{{ lock }}</h5>
            <div class="">
              <p class="card-text mb-0">Size</p>
              <div class="row">
                <div class="col-6">
                  <span>Height</span><span>{{ lock.inner_height }} inches</span>
                </div>
                <div class="col-6">
                  <span>Width</span><span>{{ lock.inner_width }} inches</span>
                </div>
              </div>
            </div>
            <div class="row mt-2 mb-3">
              <span class="col-6">Price</span
              ><span class="col-6">${{ lock.price }}</span>
            </div>
            <div class="d-flex justify-content-between align-items-center">
              <div class="">{{ lock.status }}</div>
              <a href="{% url 'create_rental' lock_id=lock.id %}" class="btn"
                >Rent</a
              >
            </div>
            <p class="card-text mt-2 text-secondary">{{ lock.location }}</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div>
      <div
        style="height: 20vh; font-weight: bolder; border-left-width: 10px"
        class="card-body px-5 my-4 rounded-0"
      >
        <h3 class="h-100 d-flex align-items-center">
          Sorry! | No locks are available for renting at this time
        </h3>
      </div>
      {% endif %}
    </div>
  </div>
  {% endblock %}
</div>

rental/templates/navbar.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-light bg-light px-2" id="mainNav">
  <div class="d-flex flex-grow-1 container">
    <div class="text-center ">
      <a href="{% url 'locks' %}" style="text-decoration: none;color: #99BC85;" class="mb-2">
        <h1 style="font-weight: bolder;" class="">LockEase</h1>
      </a>
    </div>
    <div class="flex-grow-1"></div>
    <div class="d-lg-none">
      <a
        class="btn gradient-custom-2 "
        data-bs-toggle="offcanvas"
        href="#offcanvasExample"
        role="button"
        aria-controls="offcanvasExample"
      >
        <i class="fa-solid fa-bars"></i>
      </a>
    </div>

    <!-- Offcanvas Sidebar-->
    <div
      class="offcanvas offcanvas-start d-lg-none"
      tabindex="-1"
      id="offcanvasExample"
      aria-labelledby="offcanvasExampleLabel"
    >
      <div class="offcanvas-header">
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="offcanvas"
          aria-label="Close"
        ></button>
      </div>
      <div class="offcanvas-body d-flex flex-column">
        <div
          class="border mb-4 rounded-2 d-flex flex-column justify-content-center px-4"
          style="
            height: 150px;
            font-size: 1.5em;
            font-weight: bolder;
          "
        >
          {% if user.is_authenticated %} 
          <div>
            {{ user.first_name }}
          </div>
          <div style="text-overflow: ellipsis; ">
            {{ user.email }}
          </div>
          {% else %}
          <div class="">Eventify</div>
          {% endif %}
        </div>
        <div class="d-flex flex-column gap-2 flex-grow-1">
          <a class="nav-link nav-item px-4 py-2 border rounded-2" href="{% url 'stations' %}"
            >Lock Stations</a
          >

          {% if user.is_authenticated %}

          <a
            class="nav-link nav-item px-4 py-2 border rounded-2"
            href="{% url 'rentals' %}"
            >Rentals</a
          >

          {% endif %}

          <a
            class="nav-link nav-item px-4 py-2 border rounded-2"
            href="{% url 'locks' %}"
            >Available Locks</a>

          <div class="flex-grow-1 "></div>

          {% if user.is_authenticated %}
          <a
            href="{% url 'logout' %}"
            class="btn btn-block a-lg gradient-custom-2"
            >Logout</a
          >
          {% else %}
          <a
            href="{% url 'register' %}"
            class="btn btn-block border gradient-custom-2"
            >Signup</a
          >
          <a href="{% url 'login' %}" class="btn btn-block gradient-custom-2"
            >Login</a
          >
          {% endif %}
        </div>
      </div>
    </div>

    <!-- Large Screen Navigation -->
    <div
      class="d-none d-lg-flex flex-grow-1 justify-content-between"
      id="navbarNav"
    >
      <ul class="navbar-nav d-flex flex-row gap-2 gap-xl-5 align-items-center">
        <a class="nav-link nav-item px-4 border rounded-pill" href="{% url 'stations' %}">Lock Stations</a>
        
        {% if user.is_authenticated %}
        <a class="nav-link nav-item px-4 border rounded-pill" href="{% url 'rentals' %}"
          >Rentals</a
        >
        {% endif %}

        <a class="nav-link nav-item px-4 border rounded-pill" href="{% url 'locks' %}"
          >Available Locks</a
        >
      </ul>
      <div class="d-flex align-items-center gap-4">
        {% if user.is_authenticated %}
        <a
          href="{% url 'logout' %}"
          class="btn a-lg gradient-custom-2  mx-4"
          >Logout</a
        >
        {% else %}
        <a href="{% url 'register' %}" class="btn gradient-custom-2 "
          >Signup</a
        >
        <a href="{% url 'login' %}" class="btn gradient-custom-2 "
          >Login</a
        >
        {% endif %}
      </div>
    </div>
  </div>
</nav>

rental/templates/rentals.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Rentals
{% endblock %}

{% block content %}

<div class="container">
  <h2 class="mt-2 mb-2" style="font-weight: bolder">Rentals History</h2>
  <div class="row">
    {% if page_obj %}
    <div class="row">
      {% for rental in page_obj %}
      <div class="col-lg-6 p-2 align-items-center">
        <div
          style="border-left-width: 10px"
          class="card card-body rounded-0 pt-5 pb-3"
        >
          <div class="card-title d-flex align-items-center gap-3">
            <h3>{{ rental.lock.lock_type.name }}</h3>
            <div class="border-bottom flex-grow-1"></div>
            <h3>${{ rental.lock.price }}</h3>
          </div>
          <div class="card-title d-flex align-items-center gap-3">
            <span style="font-weight: bolder" class="px-2"
              >Status: {% if not rental.status %}
              <span class="text-success">{{ rental.lock.status }}</span>
              {% else %}
              <span class="text-secondary">{{ rental.lock.status }}</span>
              {% endif %}
            </span>
            <div class=""></div>
            <span>Location: {{ rental.lock.location }}</span>
          </div>
          <div class="card-title d-flex align-items-center gap-3">
            <span>From: {{ rental.start }}</span>
            <div class=""></div>
            <span>To: {{ rental.end }}</span>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div>
      <div
        style="height: 20vh; font-weight: bolder; border-left-width: 10px"
        class="card-body px-5 my-4 rounded-0"
      >
        <h3 class="h-100 d-flex align-items-center">
          You haven't acquired any locks yet
        </h3>
      </div>
      {% endif %}
    </div>
  </div>
  {% endblock %}
</div>

rental/templates/stations.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
Lock Stations
{% endblock %}

{% block content %}

<div class="container">
  <h2 class="mt-2 mb-2" style="font-weight: bolder">Lock Stations</h2>
  <div class="row">
    {% if page_obj %}
    <div class="accordion accordion-flush gap-4 shadow my-4 py-2" id="stationsAccordion">
      {% for station in page_obj %}
      <div class="accordion-item">
        <h2 class="accordion-header" id="heading{{ forloop.counter }}">
          <button
            class="accordion-button"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#collapse{{ forloop.counter }}"
            aria-expanded="true"
            aria-controls="collapse{{ forloop.counter }}"
          >
            <div class="row w-100 align-items-center">
              <h4 class="col-6">{{ station }}</h4>
              <span class="col-6">{{ station.address }}</span>
            </div>
          </button>
        </h2>
        <div
          id="collapse{{ forloop.counter }}"
          class="accordion-collapse collapse"
          aria-labelledby="heading{{ forloop.counter }}"
          
        >
          <div class="accordion-body">
            <div class="row">
              {% for lock in station.lock_set.all %}
              <div class="col-lg-6 p-1">
                <div class="card card-body border-0 rounded-0">
                  <h5 class="card-title text-secondary">{{ lock }}</h5>
                  <div class="">
                    <p class="card-text mb-0">Size</p>
                    <div class="row">
                      <div class="col-6">
                        <span>Height</span
                        ><span>{{ lock.inner_height }} inches</span>
                      </div>
                      <div class="col-6">
                        <span>Width</span><span>{{ lock.inner_width }} inches</span>
                      </div>
                    </div>
                  </div>
                  <div class="row mt-2 mb-3">
                    <span class="col-6">Price</span
                    ><span class="col-6">${{ lock.price }}</span>
                  </div>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="">{{ lock.status }}</div>
                    <a href="{% url 'create_rental' lock_id=lock.id %}" class="btn"
                      >Rent</a
                    >
                  </div>
                  <p class="card-text mt-2 text-secondary">{{ lock.location }}</p>
                </div>
              </div>
              {% empty %}
              <h3 class="h-100 d-flex align-items-center">
                Sorry! | No locks are available for renting at this station
              </h3>
              {% endfor %}
            </div>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    {% else %}
    <div>
      <div
        style="height: 20vh; font-weight: bolder; border-left-width: 10px"
        class="card-body px-5 my-4 rounded-0"
      >
        <h3 class="h-100 d-flex align-items-center">
          Sorry! | No locks are available for renting at this time
        </h3>
      </div>
      {% endif %}
    </div>
  </div>
  {% endblock %}
</div>